### ISSUE TITLE
{Question] Is there a way to make a key binding to <isEnabledVisible value="true"/> ?

### ISSUE THREAD

**Issue by BullFlag** [jtsage/FS22_ProductionInspector#1]
Would like to toggle the Production HUD  being visible or not.     With several production chains  active it needs space

**Comment by jtsage** [comment]
In answer to your first question - the bold font is used for the production facility name, optionally elsewhere.  And yeah, I was feeling that too on the visibility keystroke.  Suggestions for a default?  Or, is it better to no-default and let you pick your own?

**Comment by BullFlag** [comment]
I'm cool with what ever you pick Ctrl+Alt +   some Num Pad Digit  for Visibilty toggle ON/OFF.    

Curious if the two inspector mods ( Vehicle and Production ) might have a binding "Overlap" bug if the both 
use the same binding for Reload XML.   Just a thought

Might take a look at no Bold on Production Facility name...  No sure any bold looks good at these small 12 pt or even 14pt fonts

**Comment by jtsage** [comment]
Overlapping keybinds in the same context (i.e. you can hit them in the same game state) seems to be indeterminate behavior in the engine.  In my experience, sometimes one works, sometimes the other, sometimes both, sometime neither. As far as I know, there isn't anything that can be done on my end for that.

Yeah, as to default, I'll just go the next key in line.  This one is 8 to reload, it'll be 7 to toggle.

As to the bold, yeah, I see what you're saying.  Let me see what happens with my current workflow if I drop the bold and up the font size just slightly on the production point name - it bothers me slightly that the name gets sort of lost on right side displays (I play with this one under the clock, vehicles above the map).  And as much as I'd like to, there isn't a good way to left justify the name of the facility - or even center it, without parsing through all of the information twice on every tick.  And one of my major issues with one of the alternatives to happylooser's vehicle one for 19 had a huge performance problem because of something like that, and I'm sensitive to it.  I've got a zoom in a few, I'll get that keybind added during :)

**Comment by BullFlag** [comment]
I just used the revision to toggle visibility, worked fine.   I needed to bind Simple Inspector Production to  Ctrl+Alt+6 for reload and Ctrl+Alt+5 for visibility toggle.

Oh... just an idea to think about,. 

       If the number one use is a quick glance to see where input  **"Material Missing "**

If the MM was RED and MM for material missing was used it would be a quick glance

<setStringTextEmptyInput value="MM"/>

Keep up the excellent design

"Simple Inspector Vehicle" and "Simple Inspector Production" would be cool naming

**Comment by jtsage** [comment]
I didn't forget about you.  I'm hesitant to do a short tag on the "Materials Missing", because right now I am pulling the l10n string from the game for that - if I roll my own, I also have to translate an abbreviation - which is a nightmare, as there isn't a great way to communicate what the original string is if you don't also speak that language.

But, I did implement the colors in the "real" version 1.0.0.1, it just dropped here.  1.0.0.0 is in testing on the modhub and should hit in the next few days - if it fails (and it might, translations are sorta ugly), I'll bump the version at the same time, otherwise there is a short cooldown before I can send them the new one.
